config/routes.rb
Ikamva::Application.routes.draw do
  resources :branches do
    resources :events do
      resources :attendance_details
    end
    resources :members
  end
  resources :uploads do
    collection do
      post :branches
      post :combined
    end
  end
  resources :attendance_record_reports

end

app/models/attendance_detail.rb
class AttendanceDetail < ActiveRecord::Base
  belongs_to :member
  belongs_to :event

  before_create :calculate_status

  private
  def calculate_status
    return unless status.blank?

    self.status = Time.now > event.late_after ? 'partial' : 'full'
  end
end

app/controllers/attendance_details_controller.rb
class AttendanceDetailsController < ApplicationController
  def new
    @branch = Branch.find(params[:branch_id])
    @event = Event.find(params[:event_id])
  end

  def create
    event = Event.find(params[:event_id])
    branch = Branch.find(params[:branch_id])

    # TODO All of this must be reaftored into the model
    begin
      member = Member.find(params[:member][:id])
    rescue
      flash[:error] = "No member with ID of #{params[:member]["id"]}"
      redirect_to new_branch_event_attendance_detail_path(branch, event)
      return
    end

    if event.members.include? member
      redirect_to new_branch_event_attendance_detail_path(branch, event)
      flash[:error] = "Attendance already captured for member with ID #{member.id}"
      return
    end

    attendance_detail = event.attendance_details.create :member_id => member.id, :status => params[:attendance_detail]["status"]
    flash[:attendance_detail] = "#{member.first_name} #{member.surname} has #{attendance_detail.status} credit"
    redirect_to new_branch_event_attendance_detail_path(branch, event)
  end

  def index
    @branch = Branch.find(params[:branch_id])
    @event = Event.find(params[:event_id])
  end

  def edit
    @branch = Branch.find(params[:branch_id])
    @event = Event.find(params[:event_id])
    @attendance_detail = AttendanceDetail.find(params[:id])
  end

  def update
    AttendanceDetail.find(params[:id]).update_attributes! params[:attendance_detail]
    flash[:attendance_detail] = "Attendance Detail updated"
    redirect_to branch_event_attendance_details_path(Branch.find(params[:branch_id]), Event.find(params[:event_id]))
  end
end

app/helpers/attendance_details_helper.rb
module AttendanceDetailsHelper
end

app/views/attendance_details/edit.erb
<h1>Edit Attendance Detail for <%= "#{@attendance_detail.member.first_name} #{@attendance_detail.member.surname}" %></h1>
<form action="<%= branch_event_attendance_detail_path(@branch, @event, @attendance_detail) %>" method="post">
  <input type="hidden" name="_method" value="put"/>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
  Status: <select name="attendance_detail[status]">
    <option value="partial" <%= "selected" if @attendance_detail.status == 'partial' %>>Partial</option>
    <option value="full" <%= "selected" if @attendance_detail.status == 'full' %>>Full</option>
  </select><p/>
  <input type="submit" value="Save"/>
</form>
<p/>
<a href="<%= branch_event_path(@branch, @event) %>">Return to Event</a>

app/views/attendance_details/index.erb
<div class="status"><%= flash[:attendance_detail] %></div>
<table>
<% @event.attendance_details.each do |detail| %>
  <tr>
    <td><%= "#{detail.member.first_name} #{detail.member.surname}" %></td>
    <td><%= detail.status.capitalize %></td>
    <td><a href="<%= edit_branch_event_attendance_detail_path(@branch, @event, detail) %>">Edit Attendance Detail</a></td>
  </tr>
<% end %>
</table>

app/views/attendance_details/new.erb
    <div class="status"><%= flash[:attendance_detail] %></div>
    <div class="error"><%= flash[:error] %></div>
    <h1>Create Attendance Detail</h1>
    <form method="post" action="<%= branch_event_attendance_details_path(@branch, @event) %>">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      Member ID: <input type="text" name="member[id]"/><p/>
      Status: <select name="attendance_detail[status]">
        <option value=''>Calculate Attendance Status</option>
        <option value='partial'>Partial</option>
        <option value='full'>Full</option>
      </select><p/>
      <input type='submit' value='Save'/>
    </form>
    <p/>
    <a href="<%= branch_events_path(@branch) %>">Return to Events</a>