config/routes.rb
Ikamva::Application.routes.draw do
  resources :branches do
    resources :events do
      resources :attendance_details
    end
    resources :members
  end
  resources :uploads do
    collection do
      post :branches
      post :combined
    end
  end
  resources :attendance_record_reports

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :events
  has_many :members
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  def index
    @branches = Branch.find(:all)
  end

  def new
  end

  def edit
    @branch = Branch.find(params[:id])
  end

  def create
    Branch.create! params[:branch]
    flash[:branch] = 'Branch Created'
    redirect_to(:action => 'index')
  end

  def update
    Branch.find(params[:id]).update_attributes! params[:branch]
    flash[:branch] = 'Branch Updated'
    redirect_to(:action => :index)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.erb
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      Name: <input type="text" name="branch[name]" value="<%= @branch.name if @branch %>"/>
      <p/>
      <input type="submit" value="Save"/>

app/views/branches/edit.erb
<h1> Edit Branch </h1>
    <form method="post" action="<%= branch_path(@branch) %>">
      <input type='hidden' value='put' name='_method'/>
      <%= render "form" %>
    </form>
    <p/>
    <a href="<%= branches_path %>">Return to Branches</a>

app/views/branches/index.erb
<div class="status"><%= flash[:branch] %></div>
<p/>
<h1>Branches</h1>
<table>
<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><a href="<%= edit_branch_path(branch) %>">Edit Branch</a></td>
    <td><a href="<%= branch_members_path(branch) %>">Members</a></td>
    <td><a href="<%= branch_events_path(branch) %>">Events</a></td>
  </tr>
  <% end %>
</table>
  <p/>
  <a href="<%= new_branch_path %>">New Branch</a>

app/views/branches/new.erb
    <h1>New Branch</h1>
    <form method="post" action="<%= branches_path %>" >
      <%= render "form" %>
    </form>
    <p/>
    <a href="<%= branches_path %>">Return to Branches</a>