config/routes.rb
Ikamva::Application.routes.draw do
  resources :branches do
    resources :events do
      resources :attendance_details
    end
    resources :members
  end
  resources :uploads do
    collection do
      post :branches
      post :combined
    end
  end
  resources :attendance_record_reports

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :branch
  has_many :attendance_details
  has_many :members, :through => :attendance_details

  def self.event_purposes
    [
      { 'branchcom' => 'Branchcom Meeting' },
      { 'careers' => 'Careers Indaba'},
      { 'computer' => 'Computer Class'},
      { 'excursion' => 'Excursion' },
      { 'holiday' => 'Holiday Programme' },
      { 'homework' => 'Homework' },
      { 'parents' => 'Parents Meeting'},
      { 'prize' => 'Prize Giving'},
      { 'talent' => 'Talent Show'},
      { 'tutorial' => 'Tutorial' },
      { 'training' => 'Volunteer Training' },
      { 'workshop' => 'Workshop' }
    ]
  end

  def late_after
    start + 20.minutes
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @purposes = Event.event_purposes
    render :layout => 'event'
  end

  def create
    Event.create! params[:event].merge "branch_id" => params[:branch_id]
    flash[:event] = "Event created"
    redirect_to branch_events_path(Branch.find(params[:branch_id]))
  end

  def index
    @branch = Branch.find(params[:branch_id])
    @events = @branch.events
  end

  def edit
    @purposes = Event.event_purposes
    @branch = Branch.find(params[:branch_id])
    @event = Event.find(params[:id])
    render :layout => 'event'
  end

  def update
    Event.find(params[:id]).update_attributes! params[:event]
    flash[:event] = "Event Updated"
    redirect_to branch_events_path(Branch.find(params[:branch_id]))
  end
end

app/helpers/event_helper.rb
module EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.erb
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      Purpose: <%= select(:event, :purpose, @purposes.map { |purpose_set| [ purpose_set.values[0], purpose_set.keys[0] ]}) %>
      <p/>
      Start: <input type='text' name="event[start]" id="start_date"/>
      <p/>
      End: <input type='text' name="event[end]" id="end_date"/>
      <p/>
      Grade: <%= select(:event, :grade, [8,9,10,11,12]) %>

      <input type='submit' value='Save'/>

app/views/events/edit.erb
<h1>Edit Event</h1>
    <form action="<%= branch_event_path(@branch, @event) %>" method="post">
      <input type="hidden" name="_method" value="put"/>
      <%= render "form" %>
    </form>
    <p/>
    <a href="<%= branch_events_path(@branch) %>">Return to Events</a>

app/views/events/index.erb
<div class="status"><%= flash[:event] %></div>
<p/>
<h1>Events for <%= @branch.name %></h1>
    <table>
      <tr>
        <th>Purpose</th>
        <th>Start</th>
        <th>End</th>
        <th>Grade</th>
      </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= (Event.event_purposes.select { |purpose_set| purpose_set.has_key? event.purpose })[0][event.purpose] %></td>
        <td><%= event.start.strftime("%Y - %m - %d %H:%M:%S %Z") %></td>
        <td><%= event.end.strftime("%Y - %m - %d %H:%M:%S %Z") %></td>
        <td><%= event.grade %></td>
        <td><a href="<%= edit_branch_event_path(@branch, event) %>">Edit Event</a></td>
        <td><a href="<%= new_branch_event_attendance_detail_path(@branch, event) %>">Add Attendance Detail</a></td>
        <td><a href="<%= branch_event_attendance_details_path(@branch, event) %>">Attendance Details</a></td>
      </tr>
    <% end %>
    </table>
    <p/>
    <a href="<%= new_branch_event_path(@branch) %>">Add Event</a><p/>
    <a href="<%= branches_path %>">Return to Branches</a>
  </body>
</html>

app/views/events/new.erb
<h1>Create Event</h1>
    <form method="post" action="<%= branch_events_path(@branch) %>">
      <%= render "form" %>
    </form>
    <p/>
    <a href="<%= branch_events_path(@branch) %>">Return to Events</a>