config/routes.rb
Ikamva::Application.routes.draw do
  resources :branches do
    resources :events do
      resources :attendance_details
    end
    resources :members
  end
  resources :uploads do
    collection do
      post :branches
      post :combined
    end
  end
  resources :attendance_record_reports

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :attendance_details
  def self.participation_types
    [{"learner"=>"Learner"}, {"volunteer"=>"Volunteer"}]
  end
  def attendance_total
    attendance_details.inject(0.0) { |total, attendance_detail| total + (attendance_detail.status == "full" ? 1.0 : 0.5) }
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @branch = Branch.find(params[:branch_id])
    @participation_types = Member.participation_types
    render :layout => "member"
  end

  def create
    member = Branch.find(params[:branch_id]).members.create! params[:member]
    flash[:member] = "Member created with ID of #{member.id}"
    redirect_to branch_members_path(:branch_id => params[:branch_id])
  end

  def index
    @branch = Branch.find(params[:branch_id])
    @participation_types = Member.participation_types
    @members = @branch.members
  end

  def edit
    @branch = Branch.find(params[:branch_id])
    @member = Member.find(params[:id])
    @participation_types = Member.participation_types
    render :layout => "member"
  end

  def update
    Member.find(params[:id]).update_attributes! params[:member]
    flash[:member] = 'Member Updated'
    redirect_to branch_members_path(Branch.find(params[:branch_id]))
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/members/_form.erb
<%= form_for([@branch, @member || Member.new]) do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<p/>
<%= f.label :surname %>
<%= f.text_field :surname %>
<p/>

<%= f.label :card_number %>
<%= f.text_field :card_number %>
<p/>

<%= f.label :gender %>
<%= f.text_field :gender %>
<p/>

<%= f.label :mobile_number %>
<%= f.text_field :mobile_number %>
<p/>

<%= f.label :telephone_number %>
<%= f.text_field :telephone_number %>
<p/>

<%= f.label :address %>
<%= f.text_field :address %>
<p/>

<%= f.label :email %>
<%= f.text_field :email %>
<p/>

<%= f.label :id_number %>
<%= f.text_field :id_number %>
<p/>

<%= f.label :grade %>
<%= f.text_field :grade %>
<p/>

<%= f.label :registration_date %>
<%= f.text_field :registration_date, :id => "registration_date" %>
<p/>

<%= f.label :participation %>
<%= f.select :participation, @participation_types.map { |type_set| type_set.to_a[0].reverse } %>
<p/>

<%= submit_tag %>
<% end %>

app/views/members/edit.erb
<h1>Edit Member</h1>
      <%= render "form" %>
    <p/>
    <a href="<%= branch_members_path(@branch) %>">Return To Member List</a>

app/views/members/index.erb
<div class="status"><%= flash[:member] %></div>
<p/>
<h1>Members for <%= @branch.name %></h1>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Card Number</th>
    <th>Participation Type</th>
  </tr>
  <% @members.each do |member| %>
    <tr>
      <td><%= member.id %>
      <td><%= "#{member.first_name} #{member.surname}" %></td>
      <td><%= member.card_number %></td>
      <td><%= (@participation_types.inject({}) { |hash,element| hash.merge! element })[member.participation] %></td>
      <td><a href="<%= edit_branch_member_path(@branch, member) %>">Edit Member</a></td>
    </tr>
  <% end %>
</table>
<p/>
<a href="<%= new_branch_member_path(@branch) %>">Create Member</a>
<p/>
<a href="<%= branches_path %>">Return to Branches</a>

app/views/members/new.erb
<h1> Create Member</h1>
  <%= render "form" %>

    <p/>
    <a href="<%= branch_members_path(@branch) %>">Return To Member List</a>